server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
   
  datasource:
    platform: postgres
    url: jdbc:postgres://ec2-54-247-119-167.eu-west-1.compute.amazonaws.com:5432/ddfoorq2e76vh4
    username: rcugvcoqqxvdye
    password: a84ce234dd40f631ddf91085c6489943fb249848316ed985c799b4584148ce22
    driverClassName: org.postgresql.Driver